
CREATE TABLE sistema_reclamo (
 id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(45) NOT NULL,
  nombre_creador VARCHAR(45) NOT NULL,
  logo   VARCHAR(200)NOT NULL,    
  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;



CREATE TABLE area (
 id INT NOT NULL AUTO_INCREMENT,
    id_sistema INT  NOT NULL,

  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(200) NOT NULL,
  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1) NOT NULL,
  PRIMARY KEY (id),
 
    FOREIGN KEY (id_sistema)
    REFERENCES sistema_reclamo (id))
ENGINE = InnoDB;


CREATE TABLE jefes_area (
 id INT NOT NULL AUTO_INCREMENT,
    id_area INT NOT NULL,

  nombres VARCHAR(150) NOT NULL,
  ap VARCHAR(200) NOT NULL,
  am VARCHAR(200) NOT NULL,
  ci INT NOT NULL,
  telefono VARCHAR(60)NOT NULL,
  correo CHAR(200) NOT NULL,
  fec_inicio DATE NOT NULL,
  fec_fin DATE  NOT NULL,
  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1) NOT NULL,
  PRIMARY KEY (id),
  
    FOREIGN KEY (id_area)
    REFERENCES area (id))
ENGINE = InnoDB;

CREATE TABLE tipo_empleado (
 id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(200) NOT NULL,
  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1) NOT NULL,
  PRIMARY KEY (id))

ENGINE = InnoDB;

CREATE TABLE empleado (
 id INT NOT NULL AUTO_INCREMENT,
  id_tipo INT NOT NULL,
   id_area INT NOT NULL,
    id_sistema INT NOT NULL,
  nombres VARCHAR(100) NOT NULL,
  ap VARCHAR(200) NOT NULL,
  am VARCHAR(200) NOT NULL,
  ci INT NOT NULL,
  tel_fijo VARCHAR(45) NOT NULL,
  tel_cel VARCHAR(45) NOT NULL,
  direccion VARCHAR(200) NOT NULL,
  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id_tipo) REFERENCES tipo_empleado(id),
  FOREIGN KEY (id_sistema) REFERENCES sistema_reclamo(id),
      FOREIGN KEY (id_area)
    REFERENCES area (id))
ENGINE = InnoDB;



CREATE TABLE horario (
 id INT NOT NULL AUTO_INCREMENT,
    id_empleado INT NOT NULL,

  hora_entrada DATETIME(6),
  hora_salida DATETIME(6),
  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1) NOT NULL,

  PRIMARY KEY (id),
    FOREIGN KEY (id_empleado)
    REFERENCES empleado (id))
  
ENGINE = InnoDB;

CREATE TABLE reclamo (
 id INT NOT NULL AUTO_INCREMENT,
  nombres VARCHAR(100) NOT NULL,
  ap VARCHAR(100) NOT NULL,
  am VARCHAR(100) NOT NULL,
  telefono INT(100) NOT NULL,
  correo CHAR(100) NOT NULL,
  codigo_usuario VARCHAR(100) NOT NULL,
  barrio VARCHAR(100) NOT NULL,
  calle_avenida VARCHAR(100) NOT NULL,
  entre_que_calles VARCHAR(100) NOT NULL,
  numero_de_casa INT NOT NULL,
  referencias VARCHAR(100) NOT NULL,
  descripcion_del_reclamo VARCHAR(100),
  map VARCHAR(100),
  otro_recurrente VARCHAR(100) NOT NULL,
  telefono_del_recurrente INT NOT NULL,
  tipo_de_calzada VARCHAR(100) NOT NULL,
  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1) NOT NULL,
  PRIMARY KEY (id)
 
  
  )
ENGINE = InnoDB;



CREATE TABLE reclamo_confirmado (
 id INT NOT NULL AUTO_INCREMENT,
  id_reclamo INT NOT NULL,
   nombres VARCHAR(100) NOT NULL,
  ap VARCHAR(100) NOT NULL,
  am VARCHAR(100) NOT NULL,
  telefono INT(100) NOT NULL,
  correo CHAR(100) NOT NULL,
  codigo_usuario VARCHAR(100) NOT NULL,
  barrio VARCHAR(100) NOT NULL,
  calle_avenida VARCHAR(100) NOT NULL,
  entre_que_calles VARCHAR(100) NOT NULL,
  numero_de_casa INT NOT NULL,
  referencias VARCHAR(100) NOT NULL,
  descripcion_del_reclamo VARCHAR(100),
  fotos VARCHAR(250),
  map VARCHAR(100),
  otro_recurrente VARCHAR(100) NOT NULL,
  telefono_del_recurrente INT NOT NULL,
  tipo_de_calzada VARCHAR(100) NOT NULL,
  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1) NOT NULL,
  
  PRIMARY KEY (id),
 FOREIGN KEY (id_reclamo) REFERENCES reclamo(id) )

   ENGINE = InnoDB;







CREATE TABLE asignacion (
 id INT NOT NULL AUTO_INCREMENT,
  id_conf INT NOT NULL,
  id_empleado INT NOT NULL,
  descripcion VARCHAR(100) NOT NULL,
  fec_inicio DATE NOT NULL,
  fec_fin DATE NOT NULL,
  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1) NOT NULL,
  PRIMARY KEY (id),
    FOREIGN KEY (id_conf)
    REFERENCES reclamo_confirmado (id),
   
    FOREIGN KEY (id_empleado)
    REFERENCES empleado (id))
   
  
    ENGINE = InnoDB;



CREATE TABLE persona(
id INT NOT NULL AUTO_INCREMENT,
 id_sistema INT NOT NULL,
 ci VARCHAR(80) NOT NULL,
 nombres VARCHAR(100)NOT NULL,
 ap VARCHAR(100),
 am VARCHAR(100),
 telefono VARCHAR(30),
 direccion VARCHAR(200),
 genero VARCHAR(90) NOT NULL,

  fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1)NOT NULL,
 PRIMARY KEY(id),
 FOREIGN KEY(id_sistema)REFERENCES sistema_reclamo(id)
)ENGINE INNODB;


CREATE TABLE usuario(
id INT NOT NULL AUTO_INCREMENT,
id_persona INT NOT NULL,
nom_usuario VARCHAR(100)NOT NULL,
clave VARCHAR(100)NOT NULL,
 fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1)NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(id_persona)REFERENCES persona(id)
)ENGINE INNODB;




CREATE TABLE rol(
id INT NOT NULL AUTO_INCREMENT,
rol VARCHAR(100)NOT NULL,
 fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1)NOT NULL,
PRIMARY KEY(id)
)ENGINE INNODB;


CREATE TABLE usuario_rol(
id INT NOT NULL AUTO_INCREMENT,
id_usuario INT NOT NULL,
id_rol INT NOT NULL,
 fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1)NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(id_usuario)REFERENCES usuario(id),
FOREIGN KEY(id_rol)REFERENCES rol(id)
)ENGINE INNODB;


CREATE TABLE grupo(
id INT NOT NULL AUTO_INCREMENT,
grupo VARCHAR(30)NOT NULL,
  icono VARCHAR(200) NOT NULL,

 fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1)NOT NULL,
PRIMARY KEY(id)
)ENGINE INNODB;



CREATE TABLE opcion(
id INT NOT NULL AUTO_INCREMENT,
id_grupo INT NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  op_url VARCHAR(200) NOT NULL,
  mostrar VARCHAR(20) NOT NULL,
  orden INT(100) NOT NULL,
 fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1)NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(id_grupo)REFERENCES grupo(id)
)ENGINE INNODB;


CREATE TABLE acceso(
id INT NOT NULL AUTO_INCREMENT,
 id_grupo INT NOT NULL,
id_opcion INT NOT NULL,
id_rol INT NOT NULL,
  permisos VARCHAR(70) NOT NULL,
 fec_insercion TIMESTAMP NOT NULL,
  fec_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usuario INT NOT NULL,
  estado CHAR(1)NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(id_grupo) REFERENCES grupo (id),

FOREIGN KEY(id_opcion) REFERENCES opcion(id),
FOREIGN KEY(id_rol)REFERENCES rol(id)
)ENGINE INNODB;




